openapi: 3.0.0
info:
  title: Twilio Messaging / SMS
  description: >-
    Ahoy!


    This Postman collection serves as a toolbelt for you to work with Twilio's
    [Programmable Messaging API](https://www.twilio.com/messaging).


    It provides functionality to interact with a subset of the Twilio API. For a
    more complete view of the API, make sure to visit our [Twilio
    Docs](https://www.twilio.com/docs/sms).


    Contact Support:
     Name: Twilio Support
     Email: support@twilio.com
  version: 1.0.0
servers:
  - url: >-
      http://{{2010-04-01-accounts-accountsid-availablephonenumbers-countrycode-local.json-url}}
  - url: http://{{2010-04-01-accounts-accountsid-incomingphonenumbers.json-url}}
  - url: http://{{2010-04-01-accounts-accountsid-messages.json-url}}
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
tags:
  - name: Getting Started
    description: >-
      Learn how to get started with Twilio Programmable Messaging by acquiring a
      phone number and sending your first SMS.
paths:
  /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Local.json:
    get:
      tags:
        - Getting Started
      summary: Find available phone numbers
      description: >-
        To send an SMS with Twilio you'll first need to buy a phone number. For
        that you have to search the catalog of available phone numbers.


        Once you have the list of available phone numbers, pick one and use it
        in the next request to buy the number.


        Learn more about this in the [Twilio
        Docs](https://www.twilio.com/docs/phone-numbers/api/availablephonenumberlocal-resource).
      security:
        - basicAuth: []
      parameters:
        - name: SmsEnabled
          in: query
          schema:
            type: boolean
          description: >-
            Whether the phone numbers can receive text messages. Can be: `true`
            or `false`.
          example: 'true'
        - name: AccountSid
          in: path
          schema:
            type: string
          required: true
          description: >-
            (Required) The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) requesting
            the AvailablePhoneNumber resources.
          example: '{{TWILIO_ACCOUNT_SID}}'
        - name: CountryCode
          in: path
          schema:
            type: string
          required: true
          description: >-
            (Required) The
            [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
            country code of the country from which to read phone numbers.
          example: US
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                available_phone_numbers:
                  - address_requirements: aute eiusmod
                    beta: true
                    capabilities: {}
                    friendly_name: nisi do
                    iso_country: voluptate
                    lata: minim cillum
                    latitude: 4649799.109687477
                    locality: in Duis ut anim irure
                    longitude: -94614168.65959848
                    phone_number: amet labore
                    postal_code: deserunt esse cillum ut
                    rate_center: velit
                    region: ipsum pariatur cupidatat dolor
                  - address_requirements: Ut
                    beta: true
                    capabilities: {}
                    friendly_name: ullamco
                    iso_country: in incididunt
                    lata: cillum dolor velit sed
                    latitude: -21235506.84035504
                    locality: sint
                    longitude: -25668838.90140347
                    phone_number: non adipisicing enim incididunt deserunt
                    postal_code: ut voluptate minim
                    rate_center: velit aliqua
                    region: Excepteur aliquip in nisi
                end: 3504435
                first_page_uri: >-
                  http://nnYdJBuOCqryvmKnbvBPBnaNMbCqrxw.tdvyHFVoZISsFUqJvqFT0cg+
                next_page_uri: >-
                  http://PoqRnDNQHgsSAILsyYutOtNGDj.qqhjm8TRty6qyZnDJAQcH1Djqzpuv,w5pf+hzR.4snyBz
                page: 90555719
                page_size: 88924560
                previous_page_uri: >-
                  https://ArZjnsEHjpSMJWeIOQAYyTOm.ispdr0ZozBph6JkyS4wCN4KsLijal5vGd-yowauXTc55dxOb
                start: -60781383
                uri: http://BJmswSvlkWlnMst.fiODjnzufdg.eBwAEpkSmwiU.e-Ygm,OFGiH
  /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers.json:
    post:
      tags:
        - Getting Started
      summary: Buy a phone number
      description: >-
        Purchase a phone-number for your Twilio account. Afterwards you can use
        this number to send or receive SMS and calls.


        Read more about it in the [Twilio
        Docs](https://www.twilio.com/docs/phone-numbers/api/incomingphonenumber-resource#create-an-incomingphonenumber-resource)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                PhoneNumber:
                  type: number
                  description: >-
                    The phone number to purchase specified in
                    [E.164](https://www.twilio.com/docs/glossary/what-e164)
                    format.  E.164 phone numbers consist of a + followed by the
                    country code and subscriber number without punctuation
                    characters. For example, +14155551234.
                  example: '+12513060906'
                AddressSid:
                  type: string
                  description: >-
                    The SID of the Address resource we should associate with the
                    new phone number. Some regions require addresses to meet
                    local regulations.
                  example: <string>
                ApiVersion:
                  type: string
                  description: >-
                    The API version to use for incoming calls made to the new
                    phone number. The default is `2010-04-01`.
                  example: <string>
                AreaCode:
                  type: string
                  description: >-
                    The desired area code for your new incoming phone number.
                    Can be any three-digit, US or Canada area code. We will
                    provision an available phone number within this area code
                    for you. **You must provide an `area_code` or a
                    `phone_number`.** (US and Canada only).
                  example: <string>
                BundleSid:
                  type: string
                  description: >-
                    The SID of the Bundle resource that you associate with the
                    phone number. Some regions require a Bundle to meet local
                    Regulations.
                  example: <string>
                EmergencyAddressSid:
                  type: string
                  description: >-
                    The SID of the emergency address configuration to use for
                    emergency calling from the new phone number.
                  example: <string>
                EmergencyStatus:
                  type: string
                  description: >-
                    The configuration status parameter that determines whether
                    the new phone number is enabled for emergency calling. (This
                    can only be one of Active,Inactive)
                  example: <string>
                FriendlyName:
                  type: string
                  description: >-
                    A descriptive string that you created to describe the new
                    phone number. It can be up to 64 characters long. By
                    default, this is a formatted version of the new phone
                    number.
                  example: <string>
                IdentitySid:
                  type: string
                  description: >-
                    The SID of the Identity resource that we should associate
                    with the new phone number. Some regions require an identity
                    to meet local regulations.
                  example: <string>
                SmsApplicationSid:
                  type: string
                  description: >-
                    The SID of the application that should handle SMS messages
                    sent to the new phone number. If an `sms_application_sid` is
                    present, we ignore all of the `sms_*_url` urls and use those
                    set on the application.
                  example: <string>
                SmsFallbackMethod:
                  type: string
                  description: >-
                    The HTTP method that we should use to call
                    `sms_fallback_url`. Can be: `GET` or `POST` and defaults to
                    `POST`. (This can only be one of
                    head,get,post,patch,put,delete,HEAD,GET,POST,PATCH,PUT,DELETE)
                  example: <string>
                SmsFallbackUrl:
                  type: string
                  description: >-
                    The URL that we should call when an error occurs while
                    requesting or executing the TwiML defined by `sms_url`.
                  example: <uri>
                SmsMethod:
                  type: string
                  description: >-
                    The HTTP method that we should use to call `sms_url`. Can
                    be: `GET` or `POST` and defaults to `POST`. (This can only
                    be one of
                    head,get,post,patch,put,delete,HEAD,GET,POST,PATCH,PUT,DELETE)
                  example: <string>
                SmsUrl:
                  type: string
                  description: >-
                    The URL we should call when the new phone number receives an
                    incoming SMS message.
                  example: <uri>
                StatusCallback:
                  type: string
                  description: >-
                    The URL we should call using the `status_callback_method` to
                    send status information to your application.
                  example: <uri>
                StatusCallbackMethod:
                  type: string
                  description: >-
                    The HTTP method we should use to call `status_callback`. Can
                    be: `GET` or `POST` and defaults to `POST`. (This can only
                    be one of
                    head,get,post,patch,put,delete,HEAD,GET,POST,PATCH,PUT,DELETE)
                  example: <string>
                TrunkSid:
                  type: string
                  description: >-
                    The SID of the Trunk we should use to handle calls to the
                    new phone number. If a `trunk_sid` is present, we ignore all
                    of the voice urls and voice applications and use only those
                    set on the Trunk. Setting a `trunk_sid` will automatically
                    delete your `voice_application_sid` and vice versa.
                  example: <string>
                VoiceApplicationSid:
                  type: string
                  description: >-
                    The SID of the application we should use to handle calls to
                    the new phone number. If a `voice_application_sid` is
                    present, we ignore all of the voice urls and use only those
                    set on the application. Setting a `voice_application_sid`
                    will automatically delete your `trunk_sid` and vice versa.
                  example: <string>
                VoiceCallerIdLookup:
                  type: string
                  description: >-
                    Whether to lookup the caller's name from the CNAM database
                    and post it to your app. Can be: `true` or `false` and
                    defaults to `false`.
                  example: <boolean>
                VoiceFallbackMethod:
                  type: string
                  description: >-
                    The HTTP method that we should use to call
                    `voice_fallback_url`. Can be: `GET` or `POST` and defaults
                    to `POST`. (This can only be one of
                    head,get,post,patch,put,delete,HEAD,GET,POST,PATCH,PUT,DELETE)
                  example: <string>
                VoiceFallbackUrl:
                  type: string
                  description: >-
                    The URL that we should call when an error occurs retrieving
                    or executing the TwiML requested by `url`.
                  example: <uri>
                VoiceMethod:
                  type: string
                  description: >-
                    The HTTP method that we should use to call `voice_url`. Can
                    be: `GET` or `POST` and defaults to `POST`. (This can only
                    be one of
                    head,get,post,patch,put,delete,HEAD,GET,POST,PATCH,PUT,DELETE)
                  example: <string>
                VoiceReceiveMode:
                  type: string
                  description: >-
                    The configuration parameter for the new phone number to
                    receive incoming voice calls or faxes. Can be: `fax` or
                    `voice` and defaults to `voice`. (This can only be one of
                    voice,fax)
                  example: <string>
                VoiceUrl:
                  type: string
                  description: >-
                    The URL that we should call to answer a call to the new
                    phone number. The `voice_url` will not be called if a
                    `voice_application_sid` or a `trunk_sid` is set.
                  example: <uri>
      security:
        - basicAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: AccountSid
          in: path
          schema:
            type: string
          required: true
          description: >-
            (Required) The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that will
            create the resource.
          example: '{{TWILIO_ACCOUNT_SID}}'
      responses:
        '201':
          description: Created
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                account_sid: ACB6
                address_requirements: foreign
                address_sid: ADeA
                api_version: reprehenderit laborum Excepteur
                beta: false
                bundle_sid: BUB2
                capabilities: {}
                date_created: incididunt ad
                date_updated: consequat nostrud non Excepteur
                emergency_address_sid: ADAd
                emergency_status: Inactive
                friendly_name: Excepteur qui aute occaecat
                identity_sid: RI4F
                origin: ex sit non
                phone_number: incididunt
                sid: PNFd
                sms_application_sid: APD1
                sms_fallback_method: put
                sms_fallback_url: https://sqnVhokvKfX.ggVS
                sms_method: delete
                sms_url: http://KvTTK.eixDOBAKnXDodC
                status: Duis est
                status_callback: >-
                  https://lukPySBKCSJZRDfZeLGCQEJiiZlrSGtT.slbsog2f2Byb3SNOpnvFCnKiEUbexVWC5tK9Qaj0IFkIVhVKN+mNB826euAwsZOYNBGrdhphsN
                status_callback_method: HEAD
                trunk_sid: TK29
                uri: >-
                  http://efvlxkNPQlPFtoHjtYEM.qceW6gOSsyL5X8uZPGhiRrpPWucrUmJlQexyf4Dl9T7ahcoPDgC3k2TRG
                voice_application_sid: AP5b
                voice_caller_id_lookup: true
                voice_fallback_method: head
                voice_fallback_url: >-
                  https://YYJSXXIemHJDgyPulvPuSDhUfIJ.ofhsUNmlqzZSTo7nnhXYYLQgunn2ScfFWt4qoJ,M2zYA,
                voice_method: PATCH
                voice_receive_mode: voice
                voice_url: >-
                  https://lNOljQzheebolftPuuCa.qjzdVdF,m6lXjsq+rV4sijQkntubbHInkrQaJO2zBraF0
  /2010-04-01/Accounts/{AccountSid}/Messages.json:
    post:
      tags:
        - Getting Started
      summary: Send an SMS
      description: >-
        Send a message from the account used to make the request with the phone
        number you purchased from Twilio in the previous step or with any other
        Twilio phone number you have associated in your account.


        Read more about it in the [Twilio
        Docs](https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                Body:
                  type: string
                  description: >-
                    The text of the message you want to send. Can be up to 1,600
                    characters in length.
                  example: Hello World!
                To:
                  type: string
                  description: >-
                    The destination phone number in
                    [E.164](https://www.twilio.com/docs/glossary/what-e164)
                    format for SMS/MMS or [Channel user
                    address](https://www.twilio.com/docs/sms/channels#channel-addresses)
                    for other 3rd-party channels.
                  example: '{{MY_PHONE_NUMBER}}'
                From:
                  type: string
                  description: >-
                    A Twilio phone number in
                    [E.164](https://www.twilio.com/docs/glossary/what-e164)
                    format, an [alphanumeric sender
                    ID](https://www.twilio.com/docs/sms/send-messages#use-an-alphanumeric-sender-id),
                    or a [Channel Endpoint
                    address](https://www.twilio.com/docs/sms/channels#channel-addresses)
                    that is enabled for the type of message you want to send.
                    Phone numbers or [short
                    codes](https://www.twilio.com/docs/sms/api/short-code)
                    purchased from Twilio also work here. You cannot, for
                    example, spoof messages from a private cell phone number. If
                    you are using `messaging_service_sid`, this parameter must
                    be empty.
                  example: '{{TWILIO_PHONE_NUMBER}}'
                AddressRetention:
                  type: string
                  description: >-
                    Determines if the address can be stored or obfuscated based
                    on privacy settings (This can only be one of retain)
                  example: <string>
                ApplicationSid:
                  type: string
                  description: >-
                    The SID of the application that should receive message
                    status. We POST a `message_sid` parameter and a
                    `message_status` parameter with a value of `sent` or
                    `failed` to the
                    [application](https://www.twilio.com/docs/usage/api/applications)'s
                    `message_status_callback`. If a `status_callback` parameter
                    is also passed, it will be ignored and the application's
                    `message_status_callback` parameter will be used.
                  example: <string>
                Attempt:
                  type: string
                  description: >-
                    Total number of attempts made ( including this ) to send out
                    the message regardless of the provider used
                  example: <integer>
                ContentRetention:
                  type: string
                  description: >-
                    Determines if the message content can be stored or redacted
                    based on privacy settings (This can only be one of retain)
                  example: <string>
                ForceDelivery:
                  type: string
                  description: Reserved
                  example: <boolean>
                MaxPrice:
                  type: string
                  description: >-
                    The maximum total price in US dollars that you will pay for
                    the message to be delivered. Can be a decimal value that has
                    up to 4 decimal places. All messages are queued for delivery
                    and the message cost is checked before the message is sent.
                    If the cost exceeds `max_price`, the message will fail and a
                    status of `Failed` is sent to the status callback. If
                    `MaxPrice` is not set, the message cost is not checked.
                  example: <number>
                MediaUrl:
                  type: string
                  description: >-
                    The URL of the media to send with the message. The media can
                    be of type `gif`, `png`, and `jpeg` and will be formatted
                    correctly on the recipient's device. The media size limit is
                    5MB for supported file types (JPEG, PNG, GIF) and 500KB for
                    [other
                    types](https://www.twilio.com/docs/sms/accepted-mime-types)
                    of accepted media. To send more than one image in the
                    message body, provide multiple `media_url` parameters in the
                    POST request. You can include up to 10 `media_url`
                    parameters per message. You can send images in an SMS
                    message in only the US and Canada.
                  example: '["<uri>","<uri>"]'
                MessagingServiceSid:
                  type: string
                  description: >-
                    The SID of the [Messaging
                    Service](https://www.twilio.com/docs/sms/services#send-a-message-with-copilot)
                    you want to associate with the Message. Set this parameter
                    to use the [Messaging Service Settings and Copilot
                    Features](https://www.twilio.com/console/sms/services) you
                    have configured and leave the `from` parameter empty. When
                    only this parameter is set, Twilio will use your enabled
                    Copilot Features to select the `from` phone number for
                    delivery.
                  example: <string>
                PersistentAction:
                  type: string
                  description: Rich actions for Channels Messages.
                  example: '["<string>","<string>"]'
                ProvideFeedback:
                  type: string
                  description: >-
                    Whether to confirm delivery of the message. Set this value
                    to `true` if you are sending messages that have a trackable
                    user action and you intend to confirm delivery of the
                    message using the [Message Feedback
                    API](https://www.twilio.com/docs/sms/api/message-feedback-resource).
                    This parameter is `false` by default.
                  example: <boolean>
                SmartEncoded:
                  type: string
                  description: >-
                    Whether to detect Unicode characters that have a similar
                    GSM-7 character and replace them. Can be: `true` or `false`.
                  example: <boolean>
                StatusCallback:
                  type: string
                  description: >-
                    The URL we should call using the `status_callback_method` to
                    send status information to your application. If specified,
                    we POST these message status changes to the URL: `queued`,
                    `failed`, `sent`, `delivered`, or `undelivered`. Twilio will
                    POST its [standard request
                    parameters](https://www.twilio.com/docs/sms/twiml#request-parameters)
                    as well as some additional parameters including
                    `MessageSid`, `MessageStatus`, and `ErrorCode`. If you
                    include this parameter with the `messaging_service_sid`, we
                    use this URL instead of the Status Callback URL of the
                    [Messaging
                    Service](https://www.twilio.com/docs/sms/services/api). URLs
                    must contain a valid hostname and underscores are not
                    allowed.
                  example: <uri>
                ValidityPeriod:
                  type: string
                  description: >-
                    How long in seconds the message can remain in our outgoing
                    message queue. After this period elapses, the message fails
                    and we call your status callback. Can be between 1 and the
                    default value of 14,400 seconds. After a message has been
                    accepted by a carrier, however, we cannot guarantee that the
                    message will not be queued after this period. We recommend
                    that this value be at least 5 seconds.
                  example: <integer>
      security:
        - basicAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/x-www-form-urlencoded
        - name: AccountSid
          in: path
          schema:
            type: string
          required: true
          description: >-
            (Required) The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that will
            create the resource.
          example: '{{TWILIO_ACCOUNT_SID}}'
      responses:
        '201':
          description: Created
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                account_sid: ACF8
                api_version: exercitation eiusmod amet laboris
                body: consectetur exercitation officia magna
                date_created: consectetur exercitation proident
                date_sent: culpa sint labore
                date_updated: proident
                direction: outbound-call
                error_code: -64742646
                error_message: nostrud sint Ut
                from: Excepteur cillum aute
                messaging_service_sid: MGDB
                num_media: dolor veniam non
                num_segments: et ut sint ut amet
                price: Lorem reprehenderit
                price_unit: Excepteur tempor i
                sid: MM79
                status: received
                subresource_uris: {}
                to: Ut non id
                uri: magna sit esse
    get:
      tags:
        - Getting Started
      summary: List all messages sent from your Twilio number
      description: >-
        Retrieve a list of messages belonging to the account used to make the
        request. You can filter for example for only the messages that were sent
        from a specific phone number.


        Read more about it in the [Twilio
        Docs](https://www.twilio.com/docs/sms/api/message-resource#read-multiple-message-resources)
      security:
        - basicAuth: []
      parameters:
        - name: From
          in: query
          schema:
            type: string
          description: >-
            Read messages sent from only this phone number or alphanumeric
            sender ID.
          example: '{{TWILIO_PHONE_NUMBER}}'
        - name: AccountSid
          in: path
          schema:
            type: string
          required: true
          description: >-
            (Required) The SID of the
            [Account](https://www.twilio.com/docs/iam/api/account) that created
            the Message resources to read.
          example: '{{TWILIO_ACCOUNT_SID}}'
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                end: 51142961
                first_page_uri: https://ZvltuXKxENEyvG.fnbzDIxrccIwHE6GxsyHjMd
                messages:
                  - account_sid: AC9E
                    api_version: commodo sint sunt eu
                    body: ut cillum
                    date_created: fugiat ipsum enim quis
                    date_sent: o
                    date_updated: laborum id esse elit
                    direction: outbound-reply
                    error_code: 89665305
                    error_message: deserunt
                    from: anim esse
                    messaging_service_sid: MGC0
                    num_media: enim et
                    num_segments: quis qui ipsum
                    price: exercitation Duis
                    price_unit: consequat qu
                    sid: SMe5
                    status: scheduled
                    subresource_uris: {}
                    to: nulla
                    uri: cillum ut in irure
                  - account_sid: ACD4
                    api_version: incididunt in non
                    body: deserunt incididunt irure eiusmod
                    date_created: sint ea
                    date_sent: Ut ut consectetur
                    date_updated: non dolore
                    direction: outbound-api
                    error_code: -69524035
                    error_message: dolore Ut officia
                    from: reprehenderit
                    messaging_service_sid: MGEe
                    num_media: voluptate fugiat eiusmod qui Ut
                    num_segments: ea
                    price: consequat
                    price_unit: fugiat aliquip
                    sid: MM38
                    status: received
                    subresource_uris: {}
                    to: in tempor labore eiusmod
                    uri: elit non dol
                next_page_uri: http://fSikGpthYZQbOt.sncsPW4TzW44TkKnuDgx8f2FJz.
                page: -43897926
                page_size: 12121047
                previous_page_uri: >-
                  https://lSrGpSrECCMzKudcyRlwJdfhlnZEaAQ.hytgI,rCvOIy,x1C6vbgTvc9p6X2hkAdrqkd5jx8JKwJPiCrpsg2w
                start: -23084704
                uri: https://USSzIQwA.hvxpmaT2476DlQGIi
